---
- name: Install UFW
  ansible.builtin.package:
    name: ufw
    state: present
- name: Allow port 8080
  community.general.ufw:
    rule: allow
    port: "8080"
    proto: tcp
- name: Enable UFW
  community.general.ufw:
    state: enabled
